### ISSUE TITLE
row hide and show not working

### ISSUE THREAD

**Issue by pradipchitrakar** [wenzhixin/bootstrap-table#1750]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/showRow-hideRow.html

The example for show hide row is not working. I also tried this in my project and did not work.

**Comment by djhvscf** [comment]
See this Pull Request: https://github.com/wenzhixin/bootstrap-table/pull/1743 it is fixed on it  @pradipchitrakar

**Comment by pradipchitrakar** [comment]
pull request https://github.com/wenzhixin/bootstrap-table/pull/1743 did not fix my issue.
i am using server side data and my html markup looks like this:
&lt;table <br />
id=&quot;the_table&quot;<br />
data-height=&quot;500&quot;<br />
data-show-columns=&quot;true&quot; <br />
data-show-toggle=&quot;true&quot; <br />
data-show-pagination-switch=&quot;true&quot; <br />
data-pagination=&quot;true&quot;<br />
data-page-list=&quot;[5,10,15,20]&quot;<br />
data-side-pagination=&quot;server&quot;<br />
data-page-size=&quot;5&quot;<br />
data-select-item-name=&quot;selectedRows&quot; <br />
data-smart-display=&quot;true&quot; <br />
data-id-field=&quot;id&quot; <br />
<br />
data-url=&quot;list.php&quot; <br />
data-method=&quot;get&quot;<br />
&gt;

I am calling the hide function as below:
$('#the_table').bootstrapTable('hideRow',{index:2});

**Comment by djhvscf** [comment]
Ok, let me check it

**Comment by wenzhixin** [comment]
Working now: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/showRow-hideRow.html
