### ISSUE TITLE
'master' documentation html printing as text error

### ISSUE THREAD

**Issue by dabros** [wenzhixin/bootstrap-table#1924]
@wenzhixin 

It seems when last update to http://bootstrap-table.wenzhixin.net.cn/documentation/ (and possibly other pages) descriptions now present as text instead of html.

For example see the `url` description, which has links.

Thought better to make this than try to **PR** as more immediate result and should be easily for merger to track what happened.

**Comment by wenzhixin** [comment]
I think that's because the `escape` option, I will check it soon.

**Comment by billzt** [comment]
You must add data-escape="false", otherwise the table would be mess!

**Comment by wenzhixin** [comment]
Consider to set the default of escape to `false`.

**Comment by wenzhixin** [comment]
fixed the documentation

**Comment by dabros** [comment]
@wenzhixin - still seeing issues around `data-query-params` line, plus can we try to remove need for horizontal scroll?

The text isnt wrapping that aggressivly so on 1920x1080 it has significant hidden content in https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/en/documentation/table-options.md, changing whole column to `col-md-10` doesnt solve, so maybe tweak layout settings so more aggressive text-wrap?
