### ISSUE TITLE
Filtered columns interfering each other

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#1981]
I'm using three columns with the input column filter, but I've just noticed they're interfering each other. When I seach in one column, it filters the results found not only in this column but also in the others.

These are the table columns:

```
<th data-field="nombre" data-sortable="true" data-filter-control="input">Poblaciones</th>
<th data-field="provincia" data-sortable="true" data-filter-control="input">Provincia</th>
<th data-field="pais" data-sortable="true" data-filter-control="input">País</th>
<th data-field="importe_portes" data-sortable="true">Importe Portes</th>
<th data-field="operate" data-formatter="formatoPortes" data-events="accionesPortes">Acciones</th>
```

And this is part of the json I get:

```
[  
   {  
      "id":"1",
      "provincias_id":"1",
      "cod_municipio":"1",
      "DC":"0",
      "nombre":"Alegr\u00eda-Dulantzi",
      "importe_portes":"0.00",
      "modified_at":"2015-11-23 16:32:46",
      "provincia":"Araba\/\u00c1lava",
      "pais":"Spain"
   },
   {  
      "id":"2",
      "provincias_id":"2",
      "cod_municipio":"1",
      "DC":"9",
      "nombre":"Abengibre",
      "importe_portes":"0.00",
      "modified_at":"2015-11-30 10:24:02",
      "provincia":"Albacete",
      "pais":"Spain"
   }
]
```

Apparently nothing misconfigured. If I search through "poblaciones", it also filters through "provincias" and "paises".

**Comment by dabros** [comment]
@luisapuyen - we really need a fiddle please, just use a subset of the json and pass in as array

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by luisapuyen** [comment]
Ok, the jsFiddle here:

[](https://jsfiddle.net/luis_apuyen/b7518dkf/)

Search for instance by "fer", go to the second page and re-run. It will display the first page.

If I remove the search text, the page cookie will work.

**Comment by luisapuyen** [comment]
I can't reproduce the issue in this case in a jsFiddle:

[example code](https://jsfiddle.net/luis_apuyen/3o7cp9bu/)

There must be some other error preventing the plugin to work correctly.

**Comment by dabros** [comment]
@luisapuyen - check console and network errors, eliminate other js resources on the page, make sure your only using `data-toggle` OR js init (not both) and that your filter functions are reachable (not contained inside $.(){ } or other type of closed scope).

**Comment by luisapuyen** [comment]
I try it out, thank you!

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by luisapuyen** [comment]
Seems that this problem has been solved with this other solution found for another issue: [#1985](https://github.com/wenzhixin/bootstrap-table/issues/1985#issuecomment-187249579)

**Comment by jamesmikesell** [comment]
I can tell you that this issue still exists in the dev branch for the filter-control (though it does not seem to be a problem in master).

Example (select a value in "column 2" and notice that column 2 contains more than just the value selected in the filter):
https://jsfiddle.net/rider2112/yk4ouLLg/

**Comment by jamesmikesell** [comment]
While looking into another issue, i think i stumbled upon the problem

Around line 534 in the dev branch there is the following if statement
```javascript 
if (this.options.sidePagination !== 'server') {
      return;
}
```

That statement used to be written in a way that it **always** evaluated false, and therefore never returned...  However got updated to it's current form as a result of 6e3410c275e25cba60013c415518ca7c46dc9277 change i believe...

Is it possible that block of code should actually be checking if the current sidePagination==='server'  ?  Or should that block of code just be removed all together?

Either way, it's causing issues as illustrated in my jsfiddle above.

**Comment by dabros** [comment]
@wenzhixin @djhvscf - thoughts on @jamesmikesell question?

**Comment by djhvscf** [comment]
I think that line of code should be changed to:

```js
if (this.options.sidePagination === 'server') {
      return;
}
```

@dabros can you open a **PR** with this change?

**Comment by dabros** [comment]
@djhvscf - im not really read into this issue at all, but changed that one line, someone can point to that commit and see if it fixes it

#2207

To link direct from fiddles, use rawgit and something like the following:

https://rawgit.com/wenzhixin/bootstrap-table/7cfbba2b67944419852c3cac8efe1ebfe69f6f1b/src/extensions/filter-control/bootstrap-table-filter-control.js

You can also point directly at your patch and any version or commit, branch, ect.

**Comment by zoltanmaric** [comment]
Hi! Thanks for fixing the issue. When will this fix be released?
