### ISSUE TITLE
Filter-control extension is broken

### ISSUE THREAD

**Issue by SasSam** [wenzhixin/bootstrap-table#2992]
The `data-filter-control="input"` doesn't work. 

It's not generating the input field, not even on the [official example page](http://issues.wenzhixin.net.cn/bootstrap-table/index.html#extensions/filter-control.html). The `select` option is working fine. The container for the filter input was generated, but the actual element is missing from it:

```
<th style="" data-field="name" tabindex="0">
  <div class="th-inner ">Item Name</div>
  <div class="fht-cell">
    <div class="filter-control"></div>
  </div>
</th>
```

I'm using the latest release (1.11.2).

**Comment by djhvscf** [comment]
Confirmed. The problem is related to filterControlPlaceholder option where it can be null or undefined. Let me create a new **PR** in order to fix this. Thanks

**Comment by nicoden** [comment]
#3010 should fix it

**Comment by wenzhixin** [comment]
Merged #3010

**Comment by zerox1212** [comment]
This is still an issue. The fixes mentioned in https://github.com/wenzhixin/bootstrap-table/issues/3021 and here have not solved this for me. Example webpage is also still broken.

If anyone else is finding this, make sure to use the file in `../src/` because I found that on the dev branch merges don't get copied to the `../dist/` folder.

**Comment by pbosavage** [comment]
I'm still experiencing this problem. I've downloaded the most recent version and tried both the ./src and ../dist files. The option for 'select' is working fine but the option for 'input' is not. Is there a resolution I am missing? Thanks.

**Comment by pbosavage** [comment]
To follow up and clarify - the ../src version will work for the 'input' option of the filter-control extension, however, I run into other problems.

If I mix the ../src version for filter-control and the ../dist version for bootstrap-table and other controls
mismatch errors occur and bootstrap-table does not work. If I use the ../src version for bootstrap-table all extension references it will work but I'll get a manifest integrity error despite the fact I'm not using a CDN. I don't know how that would behave in production.

Ideally, one would like to use ../dist for bootstrap-table and all extensions. But the 'input' filter-control does not work with this scenario.

Thank you

**Comment by pbosavage** [comment]
I hope this helps - I've gone through the javascript inports -everything will work with the exception of using the ../src version of filter-control.

In summary:

If the ../dist version of bootstrap-table and its extensions are used, everything works except filter-control does not display the 'input' filter option. 

If the ../dist version of bootstrap-table and its extensions are used, but the ../src version of filter-control is used, the 'input' filter option is displayed but the table is not loaded and the following javascript message occurs:

bootstrap-table-filter-control.js:198 Uncaught TypeError: Cannot read property 'state' of undefined
    at String.<anonymous> (bootstrap-table-filter-control.js:198)
    at Function.each (jquery-2.2.4.js:365)
    at initFilterSelectControls (bootstrap-table-filter-control.js:197)
    at BootstrapTable.initBody (bootstrap-table-filter-control.js:571)
    at BootstrapTable.initBody (bootstrap-table-editable.js:103)
    at BootstrapTable.init (bootstrap-table.js:572)
    at BootstrapTable.init (bootstrap-table-filter-control.js:534)
    at new BootstrapTable (bootstrap-table.js:277)
    at HTMLTableElement.<anonymous> (bootstrap-table.js:3066)
    at Function.each (jquery-2.2.4.js:365)
-------------------------------------------------------------------------------------------------------------------
jquery:  2.2.4
bootstrap:  3.3.7
bootstrap-table: latest

**Comment by djhvscf** [comment]
I'm working on this. I'll let you know any update

**Comment by pbosavage** [comment]
Thanks - sorry about the font on the error above - I cut and pasted from the console. Not my intention to shout it.

**Comment by zerox1212** [comment]
@djhvscf Any update?

**Comment by pbosavage** [comment]
This now works as described above but testing brings up another issue: 

when using regular search and the filter-control, the column header text is counted as part of the search data. This means if you are searching for a value that may match a column header you do not get filtered results. Has anyone else experienced this? Is there a way to exclude the column header text, as it invalidates a lot of searches.

**Comment by CorgiSong** [comment]
I tried the Develop branch and it still doesn't work for me. Can someone help me on that?

**Comment by jimgit** [comment]
Can you post a JSFIDDLE so it's easier to help?

**Comment by unregister** [comment]
hi, i also found the same issue. I'm almost frustrated. However I found this link https://codepen.io/AurelieT/pen/JGxMgo and after I try it it works. I hope this helps you.

**Comment by djhvscf** [comment]
As you can see here: https://jsfiddle.net/wenyi/e3nk137y/18165/ this is solved now.\

**Comment by vivek-kandhvar** [comment]
> As you can see here: https://jsfiddle.net/wenyi/e3nk137y/18165/ this is solved now.\

I am unable to get this working! and this fiddle doesn't work either. Can you help me share a working example?
Appreciate your help. Thanks.

**Comment by djhvscf** [comment]
See this example: https://live.bootstrap-table.com/example/extensions/filter-control.html

**Comment by zhaoou** [comment]
Hi, this is still not working for data-filter-control="input" if you have any data-filter-control after that.
Even in the example page https://live.bootstrap-table.com/example/extensions/filter-control.html,  the Item Name column doesn't have filter
