### ISSUE TITLE
Exporting selected with pagination, multiple pages selected

### ISSUE THREAD

**Issue by ggywebtech** [wenzhixin/bootstrap-table#3377]
Hi,
I've been testing a few options using the http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html and have created a jsfiddle to hopefully show the issue.
http://jsfiddle.net/ggywebtech/apseb49f/2/
When choosing to export all, the paging is taken into account and I guess disabled?
When choosing to export selected and you select more than the, E.G. data-page-size="5".
The paging does not seem to be removed and you only export the page visable.
I have found a solution but I'm not sure if it is the best idea.
 I added this code into bootstrap-table-export.js, replacing line 153 doExport with

```
if (that.options.pagination) {
     that.$el.one(that.options.sidePagination === 'server' ? 'post-body.bs.table' : 'page-change.bs.table', function () {
     doExport();
     that.togglePagination();
     });
     that.togglePagination();
}else{
     doExport();
}
```
It works but I'm not using server side!
Thanks
Regards

**Comment by wenzhixin** [comment]
Fixed in the latest version.

**Comment by DingkunLiu** [comment]
Hello! I think this issue is still here. When I use mode "selected", I am not able to export data more than one page, but only those one the current page. The debug info shows that all the selected rows were returned as `selectedData`, but whatever, they weren't exported.

**Comment by wenzhixin** [comment]
@DingkunLiu please create a new issue and provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!
