### ISSUE TITLE
Filter Control Multiple choice bug

### ISSUE THREAD

**Issue by joshuahysu** [wenzhixin/bootstrap-table#3474]
like title

**Bug1**
you can try 1 $0

[http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html)

**Bug2**
th data-field="name" data-filter-control="input">Item Name</th>//export(json,xls or..) ok
th data-field="price" data-filter-control="select">Item Price</th>  //export(json.xls or..) not ok

**Comment by jimgit** [comment]
Sorry but not seeing the bug you describe - when I select the $0 from the dropdown list I see

![image](https://user-images.githubusercontent.com/1921941/33429960-531bc49c-d594-11e7-8c3a-29c4440dcac3.png)

**Comment by joshuahysu** [comment]
![default](https://user-images.githubusercontent.com/6788495/33442791-f90c6806-d630-11e7-896e-fb8b13c38192.png)

**Comment by djhvscf** [comment]
See this commit where this issue is solved https://github.com/djhvscf/bootstrap-table/commit/2bb9d747eae338267009337a99d790bc2560902c

**Comment by manukieli** [comment]
I've update the issue, but for me the problem still.
You can see my bug report here:
https://github.com/wenzhixin/bootstrap-table/issues/3703

**Comment by dabcorp** [comment]
Hello ,

Same problem for me :

Bootstrap : 1.12.1
Bootstrap-table-cookie : 1.2.4
Bootstrap-table-filter-control : 2.1.3

Cookies is Ok , but not fired with value ( input, select )

Thx

**Comment by pelucky** [comment]
Hi,
Same problem for me:
Bootstrap table: 1.12.1。

If use Bootstrap table: 1.11.1, data-filter-control="input" can't display, like [here](https://github.com/wenzhixin/bootstrap-table/issues/3021)

Thx

**Comment by andrea-schneider** [comment]
Hi
Will this be fixed or is there any workaround? The behavior as it is isn't really suitable.

Thanks for your support

**Comment by luisbessa** [comment]
any news about a fix or a workaround? i can't have it working

thanks

**Comment by batistellabr** [comment]
Hi there. Is there any way of making filter-control work with multiple columns?

Here is my problema explained: 
https://drive.google.com/file/d/1henaUJu3Bi7XzYcWG8DXiNf0oDVWjO5n/view

Thank you.

**Comment by ktecho** [comment]
@joshuahysu  @luisbessa  @batistellabr @MrDaedra

Any of you have a working solution to be able to make filter-control work with multiple columns?

Thanks!

**Comment by ktecho** [comment]
@djhvscf It's not working yet for me with 1.13.1, which should include this fix, right?

**Comment by ktecho** [comment]
@djhvscf Just to be sure I'm doing it right:

I haven't done anything special for the filter-control to work, so it's working for me because I'm using the "search" part:
```
search: First_value_chosen_filter_1
sort: created_at
order: desc
offset: 0
limit: 20
filter: {"field_name_1":"First_value_chosen_filter_1"}
_wpnonce: aeb3d9bdc5
```
But when I select the second filter, in `search` I just have the second value. In `filter` it seems to have both values:

```
search: Second_value_chosen_filter_2
sort: created_at
order: desc
offset: 0
limit: 20
filter: {"field_name_1":"First_value_chosen_filter_1","field_name_2":"Second_value_chosen_filter_2"}
_wpnonce: aeb3d9bdc5
```

Should I use just the `filter` field and avoid using search?
