### ISSUE TITLE
OnRefresh event not passing query params

### ISSUE THREAD

**Issue by pchaganti** [wenzhixin/bootstrap-table#4195]
The onRefresh event is not getting passed the query params on the table url.

https://jsfiddle.net/pchaganti/zm1jb2vu/19/

**Comment by wenzhixin** [comment]
```
$('#eventsTable').on('refresh.bs.table', function (event, params) {

})
```

https://bootstrap-table.com/docs/faq/#is-event-parameter-put-in-the-wrong-order

**Comment by wenzhixin** [comment]
In v1.14.1, the `params` is the refresh method `params`, updated in https://github.com/wenzhixin/bootstrap-table/commit/cd96b11b41f29b03fde6c1ff13cce5c69f1534ad.

**Comment by pchaganti** [comment]
Downloaded 1.14.1 from github. query params still not being passed.

**Comment by wenzhixin** [comment]
Sorry, I meant the current version does exist the problem and fixed in the develop branch, so need to wait for the next released.

**Comment by pchaganti** [comment]
Using the develop branch with this commit. Still not getting the params passed in.

**Comment by wenzhixin** [comment]
http://dev.bootstrap-table.com/examples/

Are you using it like this?
```
$('#eventsTable').on('refresh.bs.table', function (event, params) {

})
```

![image](https://user-images.githubusercontent.com/2117018/54322155-0ef73500-462f-11e9-8e42-7d1f60c7a582.png)

**Comment by pchaganti** [comment]
Yes. 

<img width="1129" alt="Screen Shot 2019-03-13 at 8 30 35 PM" src="https://user-images.githubusercontent.com/6500/54323352-43d39f80-45cf-11e9-9678-9ad31b5b4dac.png">

**Comment by wenzhixin** [comment]
Provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports)!

**Comment by pchaganti** [comment]
Will dig into this some more and update.

thanks!

**Comment by pchaganti** [comment]
Got this to work. The issue was an earlier include that was messing it up. Thanks!

**Comment by wenzhixin** [comment]
Great!
