### ISSUE TITLE
How to remove table-bordered style and just have default Bootstrap table style.

### ISSUE THREAD

**Issue by sanjesh** [wenzhixin/bootstrap-table#446]
The style needed is this : http://getbootstrap.com/css/#tables-example
and not : http://getbootstrap.com/css/#tables-bordered

**Comment by omatic-hacker** [comment]
by default bootstrapTable class is .table and not .table-border, but if you included bootstrap-table.css , there are some borders styled ;) So don't include css or play with it (override some styles)

**Comment by sanjesh** [comment]
Thank you omatic-hacker I will play with some css

**Comment by junneyang** [comment]
I also puzzled by this problem,
is there any good solution?
thank you!

**Comment by sanjesh** [comment]
.fixed-table-container {
    border: 1px solid transparent;
}
.bootstrap-table .table>tbody>tr>td {
    border-right: 2px solid transparent;
}
.bootstrap-table .table>thead>tr>th {
    border-right: 2px solid transparent;
}
http://jsfiddle.net/wenyi/e3nk137y/11/

This would be quick fix

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/no-bordered.html

**Comment by christianwgd** [comment]
I really like this library as it has some awesome functions but every time i use this, i run into this problem. The "table-bordered" class is still not removable (in 2021!). "table-borderless" seems to have no effect and I don't think this whole css hacking is an appropriate answer. And it is not really helpful to link to a 2000 line documentation (the second link leads to a 404). 
So, can you please take this two minutes to explain how to get rid of these borders? Or simply link to some documentation that provides a solution?
Thanks a lot, Christian

**Comment by UtechtDustin** [comment]
@christianwgd Its possible and quite easy, just use the [classes](https://bootstrap-table.com/docs/api/table-options/#classes) table option.
Example which unset every class from the table: https://live.bootstrap-table.com/code/UtechtDustin/8770
