### ISSUE TITLE
StickyHeader not working with Bootstrap container or fullscreen or offset-y

### ISSUE THREAD

**Issue by aflogit** [wenzhixin/bootstrap-table#4814]
I can't get StickyHeader to work with a Bootstrap container:

1. The sticky header "jumps" out of the container, as soon as it is supposed to be at the top.
2. As well data-sticky-header-offset-y seems to have no effect: whatever value is entered, the offset is very large and always the same.
3. If fullscreen is used, the sticky header is not working at all.

Live code: [live snippet](https://live.bootstrap-table.com/code/aflogit/1612)

Replication
1. Scroll down: header "jumps" out of container
2. Change data-sticky-header-offset-y variable in HTML: no effect
3. Click on fullscreen and scroll down: header is not fixed

**Comment by wenzhixin** [comment]
Fixed in #4717: https://live.bootstrap-table.com/code/wenzhixin/1657

**Comment by UtechtDustin** [comment]
Issue still exists while resizing the window.
![Bildschirmfoto 2020-02-03 um 12 37 20](https://user-images.githubusercontent.com/13292481/73650231-f5653e80-4681-11ea-90a1-6ef6bdfec10c.png)

**Comment by wenzhixin** [comment]
Need to listen to the `resize` event to update the `stickyHeaderOffsetLeft` and `stickyHeaderOffsetRight`: https://live.bootstrap-table.com/code/wenzhixin/1658

**Comment by UtechtDustin** [comment]
You dont think that should be done within the extension ?

**Comment by wenzhixin** [comment]
I think it's hard to implement because `stickyHeaderOffsetLeft` or `stickyHeaderOffsetRight` is different in different cases.

**Comment by UtechtDustin** [comment]
Isnt it always the the left offset of the table (as in your example) ?

**Comment by wenzhixin** [comment]
If he has the menu on the left, we cannot use the offset directly.

**Comment by UtechtDustin** [comment]
But the offset is relative to the document not to the next element.
Did i miss something ?

**Comment by wenzhixin** [comment]
I will test.

**Comment by aflogit** [comment]
Thank you for fixing 1. and 3. This works great. An update of the extension would be even better.

Issue #2 hasn't been addressed yet, data-sticky-header-offset-y: whichever value > 0 it receives, the offset is always the same

**Comment by UtechtDustin** [comment]
@wenzhixin could you find out something ?

**Comment by Diagonir** [comment]
I ran into the same problem, the following changes seem to work, (only tested with `px` though) (v1.16) 
key: "renderStickyHeader",

```javascript
// allow this parameter to accept a boolean to "auto calculate" its offsets. This would avoid breaking those who already use concrete values
var stickyHeaderOffsetLeft = this.options.stickyHeaderOffsetLeft === true ? getLeftOffset(this.$el, this) : this.options.stickyHeaderOffsetLeft; 
var stickyHeaderOffsetRight = getRightOffset(stickyHeaderOffsetLeft, this.$el);
```

```javascript
function getLeftOffset($table, that) {
    var result = Math.abs($table.offset().left) + 'px';
    // Update the offset to a concrete value to prevent recalculating it over and over
    that.options.stickyHeaderOffsetLeft = result;
    return result;
}

function getRightOffset(leftOffset, $table) {
    var leftOffsetWithoutUnit = leftOffset;

    if (typeof (leftOffset) === 'string') {
        // remove any units from the leftOffset
        leftOffsetWithoutUnit = parseFloat(leftOffset.match(/[+-]?\d+(\.\d+)?/g));
    }

    var result = ($(window).width() - leftOffsetWithoutUnit - $table.parents('.fixed-table-container').width()) + 'px';

    return result;
}
```


Entire method:

```javascript
key: "renderStickyHeader",
value: function renderStickyHeader() {
  var _this3 = this;

  var that = this;
    this.$stickyHeader = this.$header.clone(true, true);

    if (this.options.filterControl) {
        $(this.$stickyHeader).off('keyup change mouseup').on('keyup change mouse', function (e) {
            var $target = $(e.target);
            var value = $target.val();
            var field = $target.parents('th').data('field');
            var $coreTh = that.$header.find('th[data-field="' + field + '"]');

            if ($target.is('input')) {
                $coreTh.find('input').val(value);
            } else if ($target.is('select')) {
                var $select = $coreTh.find('select');
                $select.find('option[selected]').removeAttr('selected');
                $select.find('option[value="' + value + '"]').attr('selected', true);
            }

            that.triggerSearch();
        });
    }

    var top = $(window).scrollTop(); // top anchor scroll position, minus header height

    var start = this.$stickyBegin.offset().top - this.options.stickyHeaderOffsetY; // bottom anchor scroll position, minus header height, minus sticky height

    var end = this.$stickyEnd.offset().top - this.options.stickyHeaderOffsetY - this.$header.height(); // show sticky when top anchor touches header, and when bottom anchor not exceeded

    if (top > start && top <= end) {
        // ensure clone and source column widths are the same
        this.$stickyHeader.find('tr:eq(0)').find('th').each(function (index, el) {
            $(el).css('min-width', _this3.$header.find('tr:eq(0)').find('th').eq(index).css('width'));
        }); // match bootstrap table style

        this.$stickyContainer.show().addClass('fix-sticky fixed-table-container'); // stick it in position

        var stickyHeaderOffsetLeft = this.options.stickyHeaderOffsetLeft === true ? getLeftOffset(this.$el, this) : this.options.stickyHeaderOffsetLeft;
        var stickyHeaderOffsetRight = getRightOffset(stickyHeaderOffsetLeft, this.$el);

        if (this.$el.closest('.bootstrap-table').hasClass('fullscreen')) {
            stickyHeaderOffsetLeft = 0;
            stickyHeaderOffsetRight = 0;
        }

        this.$stickyContainer.css('top', "".concat(this.options.stickyHeaderOffsetY));
        this.$stickyContainer.css('left', "".concat(stickyHeaderOffsetLeft));
        this.$stickyContainer.css('right', "".concat(stickyHeaderOffsetRight)); // create scrollable container for header

        this.$stickyTable = $('<table/>');
        this.$stickyTable.addClass(this.options.classes); // append cloned header to dom

        this.$stickyContainer.html(this.$stickyTable.append(this.$stickyHeader)); // match clone and source header positions when left-right scroll

        this.matchPositionX();
    } else {
        this.$stickyContainer.removeClass('fix-sticky').hide();
    }

    function getLeftOffset($table, that) {
        var result = Math.abs($table.offset().left) + 'px';
        that.options.stickyHeaderOffsetLeft = result;
        return result;
    }

    function getRightOffset(leftOffset, $table) {
        var leftOffsetWithoutUnit = leftOffset;

        if (typeof (leftOffset) === 'string') {
            leftOffsetWithoutUnit = parseFloat(leftOffset.match(/[+-]?\d+(\.\d+)?/g));
        }

        var result = ($(window).width() - leftOffsetWithoutUnit - $table.parents('.fixed-table-container').width()) + 'px';

        return result;
    }
}

```
Hope it helps

**Comment by UtechtDustin** [comment]
@Diagonir 
Could you show us your changes in the source file instead of the dist file ?

**Comment by syedsanahassan** [comment]
@wenzhixin the offset "top" param needs a "px" when it's not 0 therefore do you recommend to update https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/extensions/sticky-header/bootstrap-table-sticky-header.js#L1141 to concat  with a px?

@UtechtDustin see my comment if you want it to work just update line 1141 with px to make non-zero offset work, hope it helps
