### ISSUE TITLE
fixed-columns and stickey-header together?

### ISSUE THREAD

**Issue by dotnetshadow** [wenzhixin/bootstrap-table#4995]
Hi there,

Firstly a great library. I tried running sticky header with fixex columns and while it does work, I noticed that the stickey header doesn't lock the frozen column.

I used the online editor demo for fixed-header and added sticky-header to it
![image](https://user-images.githubusercontent.com/296247/80073922-d1800d80-858b-11ea-8119-d7879d0aab1d.png)

Basically the sticky header works and scrolls the columns together, but the fixed header columns disappear. I'm guessing I would have to manually enable that?

**Comment by wenzhixin** [comment]
Fixed in #4899

**Comment by dotnetshadow** [comment]
@wenzhixin Thanks for looking at this, but has this been fixed? 

I just did a test case and I still see the issue
https://live.bootstrap-table.com/code/dotnetshadow/3367

Basically when the sticky header is shown with fixedcolumns, scroll horizontally, the fixed column header is no longer there. In the example cell0 and cell1 should always be shown in the header, because it's fixed, but it disappears because it gets scrolled across.

**Comment by wenzhixin** [comment]
> Need to import after sticky-header when using with sticky-header extension.

https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/extensions/fixed-columns.md#note

https://live.bootstrap-table.com/code/wenzhixin/3371

**Comment by dotnetshadow** [comment]
@wenzhixin Thank you so much works perfectly well done

**Comment by dotnetshadow** [comment]
@wenzhixin I just noticed that this sample no longer works, has something changed recently?
https://live.bootstrap-table.com/code/wenzhixin/3371
