### ISSUE TITLE
Filter Control + Cookie doesn't respect default filter

### ISSUE THREAD

**Issue by jdhenry08** [wenzhixin/bootstrap-table#5111]
When using both cookie and filter control extensions, specifying a default filter value for a column is not respected on subsequent loads. See [https://live.bootstrap-table.com/code/jdhenry08/3545](https://live.bootstrap-table.com/code/jdhenry08/3545).

Note that by default, the table is filtered to '$2', and if you further filter on the name column (type '0' in the filter control, for example), it is filtered correctly. Refresh the page, and the default '$2' filter is lost (even though the '0' filter is saved correctly).

**Comment by djhvscf** [comment]
Well this is related to the precedence of the configs. If you define a filter-default value it is more important than the cookie saved. For me this is the expected behavior.

**Comment by UtechtDustin** [comment]
As @djhvscf already told this is the expected behavior, the cookie has a higher priority as the default value.
Dont use Cookies for the filtercontrol ([cookiesEnabled](https://bootstrap-table.com/docs/extensions/cookie/#cookiesenabled)) if you dont want that behavior.

Example: https://live.bootstrap-table.com/code/UtechtDustin/3826

**Comment by jdhenry08** [comment]
The two previous comments seem to contradict each other. @djhvscf says "If you define a filter-default value it is more important than the cookie saved." Then @UtechtDustin says "the cookie has a higher priority as the default value."

I agree with @djhvscf , but that's NOT the functionality I'm seeing. The cookie is overriding the filter-default value.

**Comment by UtechtDustin** [comment]
@jdhenry08 oh your right, i was confused i guess :D
In my opinion the cookie must have a higher priority as the default value.
The default value is to show a default set of the data, but if the user changes that (which has a good reason in the most cases) he want that search more than the default filter.

If someone wants always the default value, but want to use the cookie for the other stuff (page, pageSize, etc.) he can remove the filter-control extension from the cookie list (see example above).
@wenzhixin what do you think about that ?

**Comment by djhvscf** [comment]
So you expected behavior is?

1. If cookie has a filter value, use it
2. Check if filter-default value is defined
3. Usual behavior

**Comment by UtechtDustin** [comment]
Yes, first of all the cookie has the highest priority because its a wanted change of the user which works with the table.
The next step (if no cookie is set) would be the default filter.

**Comment by djhvscf** [comment]
Ok, I will be working on this change.

**Comment by djhvscf** [comment]
This is already fixed. https://live.bootstrap-table.com/code/djhvscf/5276

**Comment by jdhenry08** [comment]
I'm still seeing the same behavior in your version. See my original comment for steps to reproduce.

**Comment by jdhenry08** [comment]
@djhvscf I'm still seeing the same behavior in your version. See my original comment for steps to reproduce.
