### ISSUE TITLE
Boostrap 5 integration error

### ISSUE THREAD

**Issue by ClicShopping** [wenzhixin/bootstrap-table#5522]
Hello,

the code source of this page is based on boostrap4.5. https://examples.bootstrap-table.com/index.html?bootstrap5# not on 5.

 You can see there: https://www.clicshopping.com/ClicShoppingAdmin835 a version with boostrap5 and bootstrap table 1.18.1.
For example
Look catalog / products
Look Report/Products/viewev (export)
As you see all do not work properly.
Regards
```
<table
    id="table"
    data-bs-toggle="table" ====> add bs as new table syntax bootstrap 5
    data-id-field="selected" ===> ok
    data-select-item-name="selected[]" ====> ok
    data-click-to-select="true" 
    data-sort-order="asc" ===> ok
    data-sort-name="sort_order" ===> ok
    data-toolbar="#toolbar" ===> design 
    data-buttons-class="primary"
    data-show-toggle="true" =====> see a little pb on button aligment
    data-show-columns="true"  ====> not ok
    data-mobile-responsive="true"
   data-show-export="true" ===> not ok
>
```

Suggestion, if you can remove Jquery (bootstrap 5 do use jquery anymore), it will be better

_Originally posted by @oitsuki in https://github.com/wenzhixin/bootstrap-table/issues/5515#issuecomment-752939614_

**Comment by oitsuki** [comment]
the float does not work : float-left is float-start for example

**Comment by wenzhixin** [comment]
Fixed in #5536

**Comment by VeNoMouS** [comment]
Sorry how is this fixed?

```
   data-show-export="true" ===> not ok
```

this is still broken even in your example on the PR
