### ISSUE TITLE
Filter Extension with Table Issue

### ISSUE THREAD

**Issue by haideraliarain** [wenzhixin/bootstrap-table#561]
Add Filter to table and when u select one filter it will select all filters and will show one and not able to filter the data.

And there are not much examples with filter extension

**Comment by djhvscf** [comment]
Do you have a JSFiddle or some code?? It's difficult to understand what is happenning

**Comment by haideraliarain** [comment]
Here is JSFiddle link:
http://jsfiddle.net/haideraliarain/71x4x5qo/12/

click on one filter option you will see its selecting all filters instead of one and not filtering

I have another question. I don't like use method to give name,id, and type for filter. is there any chance i can use it through attribute on th tag. as i am generating dynamic columns that may change according to situation.

**Comment by haideraliarain** [comment]
@djhvscf , @wenzhixin any update on this issue?

**Comment by djhvscf** [comment]
@haideraliarain I already see the issue and now I'm testing why that is happening!

**Comment by dlhenke** [comment]
have you solved this problem? i'm getting the same here

**Comment by djhvscf** [comment]
@dlhenke  No sorry, I'm troubleshooting I dunno if it is a bootstrap issue or an extension issue.. But you can double check your scripts references order.. your scripts references order must be like this:

```html
<!-- jquery -->
<script src="query.min.js"></script>
<!-- plugins -->
<script src="bootstrap-table-filter.js"></script>
<script src="bs-table.js"></script>
<!-- table -->
<script src="bootstrap-table.js"></script>
<!-- extensions -->
<script src="bootstrap-table-filter.js"></script>
```

**Comment by dlhenke** [comment]
:-( nothing..  
the firefox debug tell me
TypeError: vals is undefined
this.fillFilterOptions(filter.field, vals.slice(0, 20));

my order is :
<link rel="stylesheet" href="bower_components/bootstrap-table-master/dist/bootstrap-table.min.css">
		<link rel="stylesheet" href="bower_components/bootstrap-table-filter-master/src/bootstrap-table-filter.css">
		
		<script src="bower_components/bootstrap-table-filter-master/src/bootstrap-table-filter.js"></script>
		<script src="bower_components/bootstrap-table-filter-master/src/ext/bs-table.js"></script>
		<script src="bower_components/bootstrap-table-master/dist/bootstrap-table.min.js"></script>
		<script src="bower_components/bootstrap-table-master/src/extensions/export/bootstrap-table-export.js"></script>
		<script src="bower_components/bootstrap-table-master/src/extensions/filter/bootstrap-table-filter.js"></script>
		<script src="//rawgit.com/kayalshri/tableExport.jquery.plugin/master/tableExport.js"></script>
		<script src="//rawgit.com/kayalshri/tableExport.jquery.plugin/master/jquery.base64.js"></script>

**Comment by haideraliarain** [comment]
@djhvscf  any update on this? i am running out of time.

**Comment by djhvscf** [comment]
I think I already know what is the problem @haideraliarain let me test a little bit more

**Comment by djhvscf** [comment]
Really I can see the error, but it is something related to load-success.bs.table event @haideraliarain  
@wenzhixin  can you check it out? Please

**Comment by dlhenke** [comment]
Please i know that this software is opensource, and we need to wait for a fix, if we self do not do it,
 but i do not have necessary skils to fix the problem.. 
i'm trying and trying.. no success.. 
thank you @wenzhixin @djhvscf

**Comment by djhvscf** [comment]
@dlhenke be sure that I'm testing! We will fix the issue! I will let you know when I already fix it!!

**Comment by djhvscf** [comment]
@dlhenke @haideraliarain  I already fixed the issue, I will create an example and let you know where is the code

**Comment by haideraliarain** [comment]
@djhvscf  i tested the code provided at ref, and it seems issue not yet resolved. If its working at ur end can u make example in jsfiddle, i would appreciate if you can use following example.

http://jsfiddle.net/haideraliarain/71x4x5qo/12/

**Comment by djhvscf** [comment]
@haideraliarain  Yeah! The problem is with the  new version of filter extension.. here is the code of the previous version:

http://jsfiddle.net/71x4x5qo/19/

**Comment by haideraliarain** [comment]
@djhvscf  hmm.. its working. but if filter not passed then search type functionality will be missed (i.e range, select, search, ajaxSelect). isn't it?

**Comment by djhvscf** [comment]
No, so far I can understand the plugin configures automatically the search functionality.. @haideraliarain

**Comment by samboustani** [comment]
@djhvscf, @haideraliarain is correct, the only thing showing up is a RANGE filter for each (less than, more than, equals).  Adding columns to the filter array will append them to the existing auto-generated column list.  Is there a way to clear the columns before passing it a column array with the correct type?

**Comment by djhvscf** [comment]
@samboustani Really I don't know if the bootstrap-table.js version will affect this. We have to test and modify the source code of bootstra-table-filter.js because if it is a big issue.. let me test and think what we can do!

**Comment by samboustani** [comment]
@djhvscf here are screen clips of my filters.  As you can see, the File Name is duplicated (as are others) and the filter is a range.

http://imgur.com/a/BCmwE

Also, the column with a radio button is showing up in the filter list.  Is there a way to exclude this column (if using the auto-generated filter list).  I could not find documentation.

**Comment by djhvscf** [comment]
Yes.. I will review the files! @samboustani

**Comment by Nikswann** [comment]
I second the issues with search

**Comment by djhvscf** [comment]
Go to the plugin repo to discuss this issue. https://github.com/lukaskral/bootstrap-table-filter
