### ISSUE TITLE
Fixed auto refresh not clear interval bug

### ISSUE THREAD

**Issue by saurabhsharma2u** [wenzhixin/bootstrap-table#5644]
**Bootstraptable version(s) affected**:
1.18.2
**Description**  
in below example after unchecking the refresh option, the ajax calls are still running.

**Example**  
https://live.bootstrap-table.com/code/wenzhixin/6486

**Comment by UtechtDustin** [comment]
The fix was merged in #5578, but since the merge there was no new version update.
So please wait for the next update.

**Comment by saurabhsharma2u** [comment]
@UtechtDustin thank you for reply,
i cross checked in develop branch also, this issue is still there.

**Comment by UtechtDustin** [comment]
Oh okay i can see it, the issue which was fixed in #5578 was to fix the ajax calls after the table is destroyed.
Let us check that !

**Comment by saurabhsharma2u** [comment]
when can we expect this branch to go in production?

**Comment by UtechtDustin** [comment]
@wenzhixin do you planned the next release ?

**Comment by wenzhixin** [comment]
@UtechtDustin v1.18.3 released!
