### ISSUE TITLE
side pagination = server cause filter-control does not work

### ISSUE THREAD

**Issue by zachary** [wenzhixin/bootstrap-table#5989]
### Bootstraptable version(s) affected

1.19.1

### Description

if set bootstrap-table sidepagination="server", the bootstrap-table-filter-control features will not work.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by Nao-30** [comment]
this option sends you a filter parameter to the server make sure you are using that in your query,
if so please provide an example about your exact issue
or provide screenshots about the problem

**Comment by j1v37u2k3y** [comment]
I have an example for what I think is happening:

https://live.bootstrap-table.com/code/j1v37u2k3y/10446

**Comment by tnory56** [comment]
@Nao-30 any status on this issue I think the example provided shows exactly what's happening. If not please help me understand if there is another issue or setting to make it work.

Thanks

**Comment by j1v37u2k3y** [comment]
@djhvscf right I agree what else needs to be provided? Do we need to setup something else?

**Comment by djhvscf** [comment]
Looks like this is already fixed in develop branch. https://live.bootstrap-table.com/code/djhvscf/10686

We need a new release @wenzhixin

**Comment by tnory56** [comment]
If you hit the load button on the development version it does not filter for "Item 3". So I would it is still not fixed right?

**Comment by djhvscf** [comment]
I hit the load button and the data is still filtered

**Comment by j1v37u2k3y** [comment]
The button is defined incorrectly it should be "filter". The code that is not working correctly is this:
```
$(function() {
    $button.click(function () {
      $table.bootstrapTable('filterBy', {name:['Item 3']})
    })
  })
```

I have fixed the code to replace the "load" with "filter"...

With `data-side-pagination="server"` enabled:
https://live.bootstrap-table.com/code/j1v37u2k3y/10695

Just to be clear the filterBy method should filter by that attribute when that button is pressed:

With `data-side-pagination="server"` removed:
https://live.bootstrap-table.com/code/j1v37u2k3y/10696

**Comment by tnory56** [comment]
Is there any more status on this? Or timeframe when this might be fixed?

**Comment by j1v37u2k3y** [comment]
@djhvscf I am curious as well what the status is of this issue. Thanks!

**Comment by tnory56** [comment]
Checking to see if any changes on this issue. @djhvscf

**Comment by Nao-30** [comment]
I don't really think, no i'm pretty sure that's for the "filterBy" issue described above, is NOT actually an issue, since it wasn't made for that.
now that i realized, it is not a part of the extensions.
it's one of the methods tho.
and as described in the [docs](https://bootstrap-table.com/docs/api/methods/#filterby) it can be used only on client side, that's why clearly it doesn't work when `data-side-pagination="server"` is enabled;

![image](https://user-images.githubusercontent.com/71417548/182041554-982705a8-9422-4462-99f0-93a92c0edcc2.png)

**Comment by UtechtDustin** [comment]
@Nao-30 
You're right, this is no bug.
Currently it works as designed, as you already said it's documentated in the documentation.
In the source code in the internal `onSearch` method we don't do anything if it is server-sided: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L961

But i agree we should improve that function and pass the parameter to the ajax call, which means the server could filter and return the correct data.
