### ISSUE TITLE
Duplicate headers when using tables in tabs

### ISSUE THREAD

**Issue by fabiofontesandrade** [wenzhixin/bootstrap-table#630]
When I use the bootstrap table in two tabs (bootstrap tab), the header of the table in second tab is duplicating.

The code I'm using to test:

<ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#jec" data-toggle="tab">JEC</a></li>
            <li><a href="#civel" data-toggle="tab">Cível</a></li>
        </ul>
        <div id="resultProcessosPendentes" class="tab-content">
            <div class="tab-pane fade in active" id="jec">
                <h5>
                    <small>
                        <table id="tableJEC" data-toggle="table" data-url="jec.json" data-show-columns="true"
                            data-search="true" data-show-refresh="true" data-show-export="true" data-pagination="true"
                            data-height="414">
                            <thead>
                                <tr class="white">
                                    <th data-field="id" data-sortable="true">
                                        Prazo
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Nº Processo
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Nº Processo Unificado
                                    </th>
                                    <th data-field="id" data-sortable="true">
                                        Autor
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Vara
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Comarca
                                    </th>
                                    <th data-field="id" data-sortable="true">
                                        Objeto Específico
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Objeto Geral
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Diretoria
                                    </th>
                                    <th data-field="id" data-sortable="true">
                                        Data da Audiência
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Status
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Vencimento
                                    </th>
                                </tr>
                            </thead>
                        </table>
                    </small>
                </h5>
            </div>
            <div class="tab-pane fade" id="civel">
                <h5>
                    <small>
                        <table id="tableACL" data-toggle="table" data-url="acl.json" data-show-columns="true"
                            data-search="true" data-show-refresh="true" data-show-export="true" data-pagination="true"
                            data-height="414">
                            <thead>
                                <tr class="white">
                                    <th data-field="id" data-sortable="true">
                                        Prazo
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Nº Processo
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Nº Processo Unificado
                                    </th>
                                    <th data-field="id" data-sortable="true">
                                        Autor
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Vara
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Comarca
                                    </th>
                                    <th data-field="id" data-sortable="true">
                                        Objeto Específico
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Objeto Geral
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Diretoria
                                    </th>
                                    <th data-field="id" data-sortable="true">
                                        Data da Audiência
                                    </th>
                                    <th data-field="name" data-sortable="true">
                                        Status
                                    </th>
                                    <th data-field="price" data-sortable="true">
                                        Vencimento
                                    </th>
                                </tr>
                            </thead>
                        </table>
                    </small>
                </h5>
            </div>
        </div>

**Comment by wenzhixin** [comment]
Hi @fabiofontesandrade, can you help to provide a jsFiddle base on these [templates](http://bootstrap-table.wenzhixin.net.cn/examples/#basic)?

**Comment by wenzhixin** [comment]
Fixed this bug: https://github.com/wenzhixin/bootstrap-table/commit/a6b1ec641f3a2d63bc3b7577bbbd26ce9d44ae6c

**Comment by rajeshbtlit** [comment]
Hi Wen,
I still see this problem, I am using latest i.e. 1.7 of bootstrap-table.
I have similar issue, on the second tab, i see duplicate table headers, and on click of refresh or sorting headers become one.

**Comment by fabiofontesandrade** [comment]
I am having another problem. The buttoms icons are not apperaring at the
second table (in the second tab). When I pass the mouse pointer through the
buttoms the icons appear.

2015-04-26 6:10 GMT-03:00 rajeshbtlit <notifications@github.com>:

**Comment by wenzhixin** [comment]
Can you provide some jsFiddle to show you problem? thanks @fabiofontesandrade

**Comment by rajeshbtlit** [comment]
On JsFiffle it works fine :), not sure why on my local its causing issue

**Comment by djhvscf** [comment]
Review your version of boostrap-table

**Comment by avsb93** [comment]
I am getting the same issue when I am loading the page dynamically using jquery .load()

Looking forward to the fix ASAP.

Thanks :)

**Comment by gp-manishverma** [comment]
I am also getting the same issue when using tables in the bootstrap tab ... has this resolved now?

**Comment by UtechtDustin** [comment]
@gp-manishverma please provide us an example using our [editor](https://live.bootstrap-table.com/)

**Comment by gp-manishverma** [comment]
@UtechtDustin its large project, everything is dynamic actually inside the modal there are two tabs and each tab has bootstrap-table first tab's table is working fine and whereas another table is creating duplicate header while switching tab-pane.

**Comment by gp-manishverma** [comment]
so it will take time to create json static data and HTML ... but i can send by tomorrow

**Comment by gp-manishverma** [comment]
Hi @UtechtDustin,

In my case **data-cache="false"** was the reason behind the header duplication as I removed this from table tag it seems working fine :)

**Comment by gp-manishverma** [comment]
Hi @UtechtDustin 

Here is link https://live.bootstrap-table.com/code/gp-manishverma/4006 

steps:
1. click on tab message 
2. inside the message tab click stab 2

I think now I got know what is the reason behind duplication of header :)

**Comment by UtechtDustin** [comment]
@gp-manishverma Why do you always rebuild the tables ?
It seems the destroy is the issue, without it works fine for me (https://live.bootstrap-table.com/code/UtechtDustin/4010)

**Comment by gp-manishverma** [comment]
actually there is only one function that is being called 
1. on page loading and 
2. change event from the dropdown. 

the reason behind I am destroying and then re-initializing the table on each function call is to prevent from  "**table has already initialized**" error like _datatable_ does

**Comment by UtechtDustin** [comment]
Why you dont init the table after the page is loaded ?

**Comment by gp-manishverma** [comment]
okay i am gonna do the same... Thank You
