### ISSUE TITLE
Initial sort does not work

### ISSUE THREAD

**Issue by jeje-ch** [wenzhixin/bootstrap-table#6320]
### Bootstraptable version(s) affected

1.20.2

### Description

On live example it works, but when bootstrap-table is installed with yarn and packaged with webpack, it does not.

Looking at source code, we can see that we have `this.options.data` at line `6406` instead (IMHO) of `this.data` like at line `6491` in `bootstrap-table/dist/bootstrap-table.js` file.

### Example(s)

as it works on online editor I can't create an example. Please check description above :-)

### Possible Solutions

Changing `bootstrap-table/dist/bootstrap-table.js:6406` from `this.options.data` into `this.data` do the job

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by jeje-ch** [comment]
@UtechtDustin : as stated in my description, it works in the live editor... so give you any example, I'm sorry. But as I told, something seems strange for me (IMHO) in the code => cf `Possible Solutions` part.

By the way, I was thinking to this issue this afternoon while driving, and as the target line is inside `initSearch` I thought it was linked... but I checked and the bug happen to me with and without search enabled on the table. I also test the various combination of options I have on my different tables... all of them work in your live editor :s again, I just speak about initial sort.

More, I made the suggested change on my side, and the initial sort work as expected (at least for me)

**Comment by UtechtDustin** [comment]
I don't missed the part that you can't reproduce it on editor :-)
But we need an example for test/dev purposes, we will copy & paste the code from your example to our locale dev setup.
If we found a fix we can test both (local and with our online editor).

You're suggest fix maybe fix the buf for you (temporary), but it also could cause a lot of issues.
`this.options.data` is the original dataset and `this.data` the currently shown dataset, so we must be sure it's ok to use the other one.

As soon we have a example from you we can test/fix it.

**Comment by jeje-ch** [comment]
I understand...

Here is on of my html:
```
<table id="exports-list" class="table table-striped table-bordered table-hover"
               data-toggle="table" data-locale="{{ app.request.locale|split('_')[0] }}"
               data-url="api_call_that_give_me_a_json"
               data-pagination="true"
               data-pagination-loop="false"
               data-pagination-v-align="both"
               data-page-size="20"
               data-sort-name="timestamp" data-sort-order="asc"
               data-auto-refresh="true" data-auto-refresh-interval="30"
               data-cookie="true" data-cookie-id-table="exports-list"
        >
            <thead>
            <tr>
                <th data-field="timestamp" data-sortable="true">TS</th>
                <th data-field="date" data-sortable="true">Date</th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>
```

The json is a list of items where date is the textual date (eg: 20th January 2022 14:25) and timestamp the corresponding timestep:
```
[
    {"timestamp":1576848083,"date":"20 d\u00e9cembre 2019 14:21"},
    {"timestamp":1581075878,"date":"7 f\u00e9vrier 2020 12:44"},
    {"timestamp":1581075879,"date":"7 f\u00e9vrier 2020 12:44"},
    {"timestamp":1581075880,"date":"7 f\u00e9vrier 2020 12:44"}
]
```
Hope it can help :-)

PS: I understand my solution is fine for me but should be fine tested before being published ;-)

**Comment by UtechtDustin** [comment]
Example: https://live.bootstrap-table.com/code/UtechtDustin/12357
Next time please provide us an example created by our editor, not raw code snippets.

I testet it on the editor and locally, the inital sort workes fine for me.

https://user-images.githubusercontent.com/13292481/183307141-5010905e-b9fc-4a61-b792-0cdeb779a97a.mp4

**Comment by jeje-ch** [comment]
sorry... a bit tired and as it works fine on live editor... Thank you.

I thought at a time an issue in the packaging (strange, but why not), but as I found the "strange line" (again IMHO) in the source code, it should not rely on the packaging method... and then impact everywhere... I really not understand what's happen then :/

I understood that `this.options.data` is the original data and `this.data` the modified one (because of sort, search or anything else)...

**Comment by UtechtDustin** [comment]
Do you mean this part ?
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1017

I't just copy the original dataset, which means the original dataset will not be changed at all :-)

**Comment by jeje-ch** [comment]
yes, but then you reset the previous sort done

**Comment by UtechtDustin** [comment]
No :)
```
[...this.options.data]
```
is the else part of the if in [Line 985](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L985).

So we check if we have something to filter, if we have something we do the filtering. If we don't have to filter, we set the dataset to a copy of the original dataset.

**Comment by jeje-ch** [comment]
in my case, I don't have search, so I go to the else...

before the if, my data are sorted... right after, and as we override the sort setting a copy of the original dataset, the sort is lost.

**Comment by UtechtDustin** [comment]
Sorry...maybe i miss something but:
- The code before the if in line 985 don't sort the dataset
- If i use you're example it works fine locally and if i add console.logs before and after the if/else, all datasets (`this.options.data` and `this.data`) has the SAME data and the SAME sorting/filtering.
- [Line 982,1018](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L982-L1018) is needed for the [filterBy](https://bootstrap-table.com/docs/api/methods/#filterby) method. Not for the sorting/search input.
- The real "search" (which you don't use) is done in [Line 1022-1108](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1022-L1108)
- The sort can't be overwritten by the else part because the sort is the last call in the `initSearch` method in [Line 1114](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1114).

So i don't see an bug there, if you think there is a bug we need a example to reproduce it.

Wir können auch gerne in Deutsch weitert schreiben wenn es dir hilft :-)

**Comment by jeje-ch** [comment]
when you come from the `load` method, the sort is already done in the `initData` method, called before the `initSearch`. But you're right that the `initSort` and the end of `initSearch` should then re-do the job... but it does not (in my case... see below why ;-) )
I suppose in some case (depending the `initSearch` caller), this.data may be not initialized... but in such case I think it should be before anything in the `initSearch`, not where he could override previous data

I understood what's happen...

I've a javascript module, where I load bootstrap-table and some extensions I use (may be not in all table, but...). And one of this extension is reorder-rows, which is not used in the given example (but code is still loaded) and which override (a bit) the initSearch and initSort methods... and it set a `ignoreInitSort` boolean !

So, if you don't load the `reorder-rows` extension, the `initSort` at the end of the `initSearch` make the job; otherwise, it's skipped :-)

Sorry but I can't no more German :/

**Comment by UtechtDustin** [comment]
Okay, now i understand the issue.
You mean this part: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/reorder-rows/bootstrap-table-reorder-rows.js#L132-L135

Maybe you now understand why we ask for examples in the editor. If you had provided one, i instantlly could see that you also use the reorder-rows extension.
In that case we could have skipped  the last posts :P

We will check this, thanks for the information.

**Comment by jeje-ch** [comment]
but I probably forgot that extension, as I don't use it in most of my tables. I understood since the begining the need of example ;-)

and line 126 also (which set the boolean)

will change the way I load the reorder-row in the meanwhile ;-) thank you

**Comment by UtechtDustin** [comment]
@wenzhixin
This bug exists because of #5682, could you maybe explain the issue of this PR ?
I'm not quite sure which bug was fixed by this PR.

**Comment by manhart** [comment]
The problem described here still exists. [Example](https://live.bootstrap-table.com/code/manhart/19003)
We have to patch every release manually by commenting out  

```js
// this.ignoreInitSort = true;
```

in `bootstrap-table-reorder-rows.js`

This has been reported back in 2022 - may I kindly ask why it is still unresolved?
Is there a plan to fix it, or should we consider maintaining our own fork for this?

[https___github_com_wenzhixin_bootstrap-table_issues_6320.patch](https://github.com/user-attachments/files/22234726/https___github_com_wenzhixin_bootstrap-table_issues_6320.patch)
